Tuples is simillar to a list. It is defined using `( )`.

In [5]:
# Tuples 
aTuple = (3,'4',3)

aTuple*3
aTuple.count(3)

2

The difference of a Tuple with a List: a Tuple is immutable while a List is mutable.


*   You can not change an element in a tuple.
*   You can however change the entire tuple.

In [20]:
# Tuples
aTuple = (3,'4',3)

# List
aList = [3,'4',3]

# tuples are immutable (it is fixed, cannot replace the items)
# lists are mutable

print(aTuple)
print(aList)
aList[0] = 5

#aTuple = [5.,'4',3]


print(aTuple)
print(aList)

(3, '4', 3)
[3, '4', 3]
(3, '4', 3)
[5, '4', 3]

In [21]:
# convert
print(type(aTuple))
v = list(aTuple)
print(v)
v[0] = 1
print(v)

<class 'tuple'>
[3, '4', 3]
[1, '4', 3]