In [9]:
a = 4
b = 3
c = 7
print(a)
print(b)

4
3

In [10]:
print(c)

7

In making string, python does not differentiate between single and double quotes.

In [12]:
d = 'Hello'
e = "Nophi likes purple"
print(d,e)
print(a,b,c)

Hello Nophi likes purple
4 3 7



*   Multiple strings or characters can be 
used a variable as long as it is not a reserved keyword.
*   Varibale names cannot start with a number.

*   Only the underscore '_' special character can be used for variable name.

*   The '#' is a python keyword for comments which means anything after it on the same line will be ignored by python.

*   The shotcut key for comment is CTRL + ?

In [14]:
# comment. Python will ignore this line  
filter_Order = 2048 # comment after the code
data2plot = 3

In [16]:
# mutiple assignments
f,g = 10,20
print(f,g)

10 20

In order to remember or show all the variables that were created, use th `%whos` command.

In [17]:
%whos

Variable       Type    Data/Info
--------------------------------
a              int     4
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20

In [ ]:
# Exercise:
# 1) can you over-write a variable in the same type
# 2) can you over-write a variable using a different data type

In [19]:
# let value of x
x = 1

In [20]:
%whos

Variable       Type    Data/Info
--------------------------------
a              int     4
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20
x              int     1

In [21]:
# change value of variable x
x = 2

# check whether value has changed
%whos

Variable       Type    Data/Info
--------------------------------
a              int     4
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20
x              int     2

Yes you can change variable value for int

In [23]:
# try for string
name = 'nophi'

%whos

Variable       Type    Data/Info
--------------------------------
a              int     4
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20
name           str     nophi
x              int     2

In [24]:
# change the value of name
name = 'ian'

%whos

Variable       Type    Data/Info
--------------------------------
a              int     4
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20
name           str     ian
x              int     2

Yes, the value of the variable with type string can be changed.

In [27]:
# changing the data type
x = 'Nophi'
%whos

Variable       Type    Data/Info
--------------------------------
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20
name           str     ian
x              str     Nophi

Yes, the variable type can be changed from int to string.

In [29]:
# changing data type from string to int
x = 23
%whos

Variable       Type    Data/Info
--------------------------------
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20
name           str     ian
x              int     23

Yes, the variable data type can be change from string to int.

In [25]:
# deleting a variable
del a

%whos

Variable       Type    Data/Info
--------------------------------
b              int     3
c              int     7
d              str     Hello
data2plot      int     3
e              str     Nophi likes purple
f              int     10
filterOrder    int     2048
filter_Order   int     2048
g              int     20
name           str     ian
x              int     2